const members_2021 = [
	{
		name: "Rushikesh Wayal",
		image:"http://drive.google.com/uc?export=view&id=1fJKnvxYUOsbms81mRpn7g3Ovg4tq8Ubn",
		linkedin: "https://www.linkedin.com/in/rushikesh-wayal/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2021,
		workplace: "AlphaGrep",
		designation: "",
		additional_info: "",
	},
	{
		name: "Dibya Prakash Das",
		image:"http://drive.google.com/uc?export=view&id=14VeMFA1qHIAFlBADo4L_V5Oc3xn-fyoM",
		linkedin: "https://www.linkedin.com/in/dibya-prakash-das/",
		degree: "Mathematics",
		graduation_year: 2021,
		workplace: "Bidgely",
		designation: "",
		additional_info: "",
	},
	{
		name: "Supriya Gupta",
		image:"http://drive.google.com/uc?export=view&id=1kcSjrarOGfR_zgK9_zoFE9Hpmqmp-9VA",
		linkedin: "https://www.linkedin.com/in/supr1ya-gupta/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2021,
		workplace: "JP Mogan Chase & Co",
		designation: "",
		additional_info: "",
	},
	{
		name: "Anju Joon",
		image:"http://drive.google.com/uc?export=view&id=1cuvFzPW-bdIf9YoTPcfO-gWQHoTcmrda",
		linkedin: "https://www.linkedin.com/in/anju-joon-27099a128/",
		degree: "Humanities and Social Sciences",
		graduation_year: 2021,
		workplace: "UPSC",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sounak Saha",
		image:"http://drive.google.com/uc?export=view&id=1wbWUcYQ3f9Z3prrDxDepMq8DGZrzvUwL",
		linkedin: "https://www.linkedin.com/in/sounak-saha-a8840ab8/",
		degree: "Biotechnology",
		graduation_year: 2021,
		workplace: "Graduate Researcher, University of Illinois Urbana-Champaign",
		designation: "",
		additional_info: "",
	},
	{
		name: "Kankana Haldar",
		image:"http://drive.google.com/uc?export=view&id=11yTtHoBRDcg1wuTN9WEHqJubszGlxuyS/view?usp=sharing",
		linkedin: "https://www.linkedin.com/in/kankana-haldar-3313a6147/",
		degree: "Electrical Engineering",
		graduation_year: 2021,
		workplace: "American Express",
		designation: "",
		additional_info: "",
	},
];

export default members_2021;
