const members_2020 = [
	{
		name: "Siddharth Singh",
		image:"http://drive.google.com/uc?export=view&id=1cqJCGQPWPlHlYkB0cYxHjPwErLhtuQ6E",
		linkedin: "https://www.linkedin.com/in/siddharth-singh-a7232a114/",
		degree: "Computer Science Engineering",
		graduation_year: 2020,
		workplace: "University of Maryland",
		designation: "Graduate Research Assistant",
		additional_info: "",
	},
	{
		name: "Saumo Pal",
		image:"http://drive.google.com/uc?export=view&id=1WLx7GvZdMZbjjiTpt3q3XHl-IRZPpKhx",
		linkedin: "https://www.linkedin.com/in/saumo-pal/",
		degree: "ECE",
		graduation_year: 2020,
		workplace: "Dive",
		designation: "SDE",
		additional_info: "Cofounder, Gerryeats",
	},

	{
		name: "Dhiraj Kumar",
		image:"http://drive.google.com/uc?export=view&id=1vpUgVKX640PiM9FHGz3lYficMUxB0znj",
		linkedin: "https://www.linkedin.com/in/dhiraj-kumar-b18712119/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "Synaptic",
		designation: "CoinSwitch Kuber",
		additional_info: "",
	},
	{
		name: "Amirneni Satakarni",
		image:"http://drive.google.com/uc?export=view&id=1qY5Og_lRDtn1ktRODUuJkodrxIhuyO-G",
		linkedin: "https://www.linkedin.com/in/satakarni-amirneni/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2020,
		workplace: "Microsoft",
		designation: "",
		additional_info: "",
	},
	{
		name: "Talluri Surya Teja",
		image:"http://drive.google.com/uc?export=view&id=1ksghX-MCf6oh94cXKou51vtMse16j59x",
		linkedin: "https://www.linkedin.com/in/surya-teja-talluri-383532103/",
		degree: "Electrical Engineering",
		graduation_year: 2020,
		workplace: "MathWorks",
		designation: "",
		additional_info: "",
	},
	{
		name: "Shubham Kumar Dubey",
		image:"http://drive.google.com/uc?export=view&id=1Txs1Kc1deV08nnu4w0IIkCawLDr5dw3T",
		linkedin: "https://www.linkedin.com/in/shubham-dubey-20b828115/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "American Express",
		designation: "",
		additional_info: "Citi India",
	},
	{
		name: "Rahul Das",
		image:"http://drive.google.com/uc?export=view&id=1zgjCU7DcEpWCXAVXrZuh8z9bRW6ZAH87",
		linkedin: "https://www.linkedin.com/in/rahuldas55/",
		degree: "Mathematics",
		graduation_year: 2020,
		workplace: "Rubrik",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ankit Agarwal",
		image:"http://drive.google.com/uc?export=view&id=1gR7Ut8-wffOrEbWdKSYIc_gWsUVaCCju",
		linkedin: "https://www.linkedin.com/in/ankit-agarwal-profile/",
		degree: "Humanities and Social Sciences",
		graduation_year: 2020,
		workplace: "Nomura",
		designation: "",
		additional_info: "Credit Suisse",
	},
	{
		name: "Ojas Agarwal",
		image:"http://drive.google.com/uc?export=view&id=1WEC6h3hvMgeRUgDfBbDlbHWVTwZNtwhH",
		linkedin: "https://www.linkedin.com/in/ojasagarwal97/",
		degree: "Ocean Engineering and Naval Architecture",
		graduation_year: 2020,
		workplace: "Sprinklr",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sushovan Haldar",
		image:"http://drive.google.com/uc?export=view&id=1F-ylZSFniyYoMgo2J4_lZA2faFX9hMu2",
		linkedin: "https://www.linkedin.com/in/sushovan-haldar-23a534113/",
		degree: "Mathematics",
		graduation_year: 2020,
		workplace: "HSBC",
		designation: "Evalueserve",
		additional_info: "",
	},
	{
		name: "Ruchita Das",
		image:"http://drive.google.com/uc?export=view&id=1f9hreR1CcECkj4IChAiM-fCursvpiGqg",
		linkedin: "https://www.linkedin.com/in/ruchitadas3938/",
		degree: "Mathematics",
		graduation_year: 2020,
		workplace: "Microsoft",
		designation: "",
		additional_info: "",
	},
	{
		name: "Bharghav D",
		image:"http://drive.google.com/uc?export=view&id=1csUzINI-lHBM_W5B9RKhnR0QNjPMJ4DA",
		linkedin: "https://www.linkedin.com/in/bhargav-dindukurthi/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "Cadence Design Systems",
		designation: "Adobe",
		additional_info: "Stanford University",
	},
	{
		name: "Rishav Sharma",
		image:"http://drive.google.com/uc?export=view&id=1BlQ7aurdTcw8xWzQHlTzb-03schhw8M5",
		linkedin: "https://www.linkedin.com/in/rishav-sharma-9762a6131/",
		degree: "Civil Engineering",
		graduation_year: 2020,
		workplace: "Millenium",
		designation: "JPMorgan Chase & Co",
		additional_info: "",
	},
	{
		name: "G Vishal",
		image:"http://drive.google.com/uc?export=view&id=1i8TblXAn3b9D5z8uPh4BHjiwj890vezW",
		linkedin: "https://www.linkedin.com/in/vishal-garimella-674b56125/",
		degree: "Computer Science and Engineering",
		graduation_year: 2020,
		workplace: "Microsoft",
		designation: "Goldman Sachs",
		additional_info: "",
	},
	{
		name: "Soumava Paul",
		image:"http://drive.google.com/uc?export=view&id=1sD6FltNl13WAFPyLlTxJdSgheLyx9mZV",
		linkedin: "https://www.linkedin.com/in/mvp18/",
		degree: "Electrical Engineering",
		graduation_year: 2020,
		workplace: "Research Assistant, Max Planck Institute for Informatics",
		designation: "Universität des Saarlandes",
		additional_info: "",
	},
	{
		name: "Sanskar Agarwal",
		image:"http://drive.google.com/uc?export=view&id=1nkadSHOPsr-detdneGYENj_NT7eDtrTn",
		linkedin: "https://www.linkedin.com/in/sanskar97/",
		degree: "Electrical Engineering",
		graduation_year: 2020,
		workplace: "Preimage",
		designation: "Intel Labs",
		additional_info: "",
	},
	{
		name: "L Pavan Kumar",
		image:"http://drive.google.com/uc?export=view&id=1DBcn_356lgtACNRlgHenW3xKkPZj7jDm",
		linkedin: "https://www.linkedin.com/in/lanke-pavan-kumar-535a23148/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2020,
		workplace: "Audit Partnership Ltd",
		designation: "Brillio",
		additional_info: "",
	},
	{
		name: "Anjali Jha",
		image:"",
		linkedin: "https://www.linkedin.com/in/anjalijha167/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "Woodline Partners",
		designation: "Goldman Sachs",
		additional_info: "University of California, Berkeley",
	},
	{
		name: "Chinmay Sawkar",
		image:"",
		linkedin: "https://www.linkedin.com/in/chinmay997/",
		degree: "Manufacturing",
		graduation_year: 2020,
		workplace: "Apple",
		designation: "SDE Intern",
		additional_info: "Graduate Teaching Assistant, Texas A&M University",
	},
];

export default members_2020;
