const members_2018 = [
	{
		name: "Ankush Chatterjee",
		image:"http://drive.google.com/uc?export=view&id=1SJvjEzZbu2kLK53TdQXtGMA39lKn3u6P",
		linkedin: "https://www.linkedin.com/in/ankushchatterjee/",
		degree: "Mathematics",
		graduation_year: 2018,
		workplace: "Google",
		designation: "Data and Applied Scientist, Microsoft",
	},
	{
		name: "Utkarsh C Doshi",
		image:"http://drive.google.com/uc?export=view&id=1plrkmcfSYfqCHcujAgM1UIHhosUBxm2t",
		linkedin: "https://www.linkedin.com/in/utkarshcdoshi/",
		degree: "Metallurgical and Materials Engineering",
		graduation_year: 2018,
		workplace: "WorldQuant",
		designation: "Analyst, JP Morgan",
	},
	{
		name: "Aakanksha Sangwan",
		image:"http://drive.google.com/uc?export=view&id=1c4UC1mf7SF-f3wEwAfKRScVQ7sBH2AQI",
		linkedin: "https://www.linkedin.com/in/sangwanaakanksha/",
		degree: "Physics",
		graduation_year: 2018,
		workplace: "University Of Southern California",
		designation:
			"Associate Manager, Quality Council of India(QCI) | Deputy Manager, Chief Minister's Good Governance Associate Programme",
		additional_info: "MS",
	},
	{
		name: "Vyom Shrivastav",
		image:"http://drive.google.com/uc?export=view&id=1pStgx02xmHh1CDzuMjjLT9Sg3mwdTd3S",
		linkedin: "https://www.linkedin.com/in/vyomshrivastava/",
		degree: "Mechanical Engieering",
		graduation_year: 2018,
		workplace: "",
		designation: "Data Scientist and Advisor, Schlumberger",
		additional_info: "MBA",
	},
	{
		name: "Kartikeya Singh",
		image:"http://drive.google.com/uc?export=view&id=1X5bIbOGXB4sbRjcmE2nigmw-Ux4xjtiC",
		linkedin: "https://www.linkedin.com/in/kartikeya212/",
		degree: "Economics",
		graduation_year: 2018,
		workplace: "Kotak Mahindra Asset Management Companies",
		designation: "Research Manager, Kantar",
	},
	{
		name: "Adarsh Upadhayay",
		image:"http://drive.google.com/uc?export=view&id=1ZaG7S6zHGBqME4xnaa9i-eUWUMdyLBPi",
		linkedin: "https://www.linkedin.com/in/adarshupadhyay43/",
		degree: "Economics",
		graduation_year: 2018,
		workplace: "Amazon",
		designation: "Data Scientist, OLX Groups | Consultant, ZS Associates",
	},
	{
		name: "Neeraj Bhukania",
		image:"http://drive.google.com/uc?export=view&id=1U3DYcGuEBB6WaoDQdrd07Uowj-Jy9w5s",
		linkedin: "https://www.linkedin.com/in/neeraj-bhukania/",
		degree: "Mathematics",
		graduation_year: 2018,
		workplace: "Jio",
		designation: "Assistant Manager, American Express",
	},
	{
		name: "Kaustubh Mani",
		image:"http://drive.google.com/uc?export=view&id=1G-G86IlWFd7mtKO0C7elRc54J-jaeaGt",
		linkedin: "https://www.linkedin.com/in/kaustubh-mani/",
		degree: "Geology and Geophysics",
		graduation_year: 2018,
		workplace: "Sponsored research and Consultancy, IIT Kharagpur",
		additional_info: "",
	},
	{
		name: "Challaram Vikas Reddy",
		image:"http://drive.google.com/uc?export=view&id=1nmL2vsAK75z37BRKNOuEeFtynLI9161c",
		linkedin: "https://www.linkedin.com/in/vikasreddyc/",
		degree: "",
		graduation_year: 2018,
		workplace: "Ignition",
		designation: "Bettr | Cliqery(Founder)",
	},
	{
		name: "Ayush Bhargava",
		image:"http://drive.google.com/uc?export=view&id=12on65Rn-Y17xL08A1TOQpKVKke7NAKOS",
		linkedin: "https://www.linkedin.com/in/ayush-bhargava-428a4a97/",
		degree: "Mathematics",
		graduation_year: 2018,
		workplace: "Goldman Sachs",
		designation: "Software Engineer, VISA",
		additional_info: "MBA",
	},
	{
		name: "Rahul Agarwal",
		image:"http://drive.google.com/uc?export=view&id=1cADAB4YyvGiheuq_VHV6XA3DzD5BKFjH",
		linkedin: "https://www.linkedin.com/in/rahul-agarwal-8937967b/",
		degree: "",
		graduation_year: 2018,
		workplace: "Atlassian",
		designation: "Member, Oracle | Senior Software Developer, Blitz Growth Inc",
	},
	{
		name: "Abhinav Agarwalla",
		image:"http://drive.google.com/uc?export=view&id=19wdHKw-k9Lqb1y5TtA5gKCwl6pmTdEFj",
		linkedin: "https://www.linkedin.com/in/abhinavagarwalla/",
		degree: "Mathematics",
		graduation_year: 2018,
		workplace: "Neural Magic",
		designation: "Data Scientist, Microsoft",
		additional_info: "MS",
	},
	{
		name: "Divya Shrivastava",
		image:"http://drive.google.com/uc?export=view&id=1mJU35jeQrhNxkN82WBdo2bRBH_Q3BtwM",
		linkedin: "https://www.linkedin.com/in/divyashrivastava2203/",
		degree: "Chemical Engineering",
		graduation_year: 2018,
		workplace: "Tata Nexarc",
		designation: "Manufacturing Manager, Uniliver",
		additional_info: "MBA",
	},
	{
		name: "Atul Patel",
		image:"http://drive.google.com/uc?export=view&id=1oWoOFq4KPSndYDHVGw3UWBzP2L0lHJgW",
		linkedin: "https://www.linkedin.com/in/atul-patel-1146b6b5/",
		degree: "Electrical Engineer",
		graduation_year: 2018,
		workplace: "PayU",
		designation: "Assistant Manager, American Express",
	},
	{
		name: "Chinmoy Samant",
		image:"http://drive.google.com/uc?export=view&id=1qPKMoIzl5nrThL9ypyKiY6ak7ur7BnUo",
		linkedin: "https://www.linkedin.com/in/chinmoy7/",
		degree: "Electrical Engineer",
		graduation_year: 2018,
		workplace: "Salesforce",
		designation: "Teaching Assistant, University of Austin",
		additional_info: "MS",
	},
	{
		name: "Amit Kumar Pandey",
		image:"http://drive.google.com/uc?export=view&id=12MGV_7jynstCmiG_PXntYpSAWyB3kufe",
		linkedin: "https://www.linkedin.com/in/amit-pandey-677b26103/",
		degree: "Mechanical Engineering",
		graduation_year: 2018,
		workplace: "PwC Acceleration Centre",
		designation: "Consultant, TCG Digital",
	},
	{
		name: "Shubham Dhal",
		image:"http://drive.google.com/uc?export=view&id=1NCTBk9GPq6RJb6LaioBuFFSG4RmfQqd-",
		linkedin: "https://www.linkedin.com/in/shubham-dhal-349626ba/",
		degree: "Mechanical Engineering",
		graduation_year: 2018,
		workplace: "ShareChat",
		designation: "Quantitative Researcher, J.P Morgan",
	},
	{
		name: "Anukul Kumar",
		image:"http://drive.google.com/uc?export=view&id=1sgHUAyF_TiZb81h49hyGIMl3odmVPKVl",
		linkedin: "https://www.linkedin.com/in/anukul-kumar/",
		degree: "Civil Engineering",
		graduation_year: 2018,
		workplace: "Founding Member, Density Exchange",
		designation: "Software Engineer, Mercari",
	},
	{
		name: "Sarath",
		image:"http://drive.google.com/uc?export=view&id=1IO8EhKUh9UMZZMXdbw4DfL1jRPC3epjU",
		linkedin: "https://www.linkedin.com/in/sarath-nookala/",
		degree: "Mechanical",
		graduation_year: 2018,
		workplace: "Meta",
		designation: "Goldman Sachs",
	},
	{
		name: "Shubham Chandak",
		image:"http://drive.google.com/uc?export=view&id=1UWL4v1NCPuu_jakltK0V04O6Sjdv_mA6",
		linkedin: "https://www.linkedin.com/in/shubham-chandak/",
		degree: "Mining",
		graduation_year: 2018,
		workplace: "Bloomberg",
		designation: "Medibuddy, Bajaj Finserv",
	},
	{
		name: "Sourav Choudhary",
		image:"http://drive.google.com/uc?export=view&id=1iAbXYgf24_i8RhUGWMDwvcCIsN9B1hDt",
		linkedin: "https://www.linkedin.com/in/sourav-choudhary-ab1464a0/",
		degree: "Mechanical",
		graduation_year: 2018,
		workplace: "C2FO",
		designation: "Capital One",
	},
	{
		name: "Rajat Garg",
		image:"http://drive.google.com/uc?export=view&id=1418lCMR1dxX_Zuu5UGY8wVdJckqGKBm-",
		linkedin: "https://www.linkedin.com/in/rajatgarg-iitkgp/",
		degree: "Computer Science Engineering",
		graduation_year: 2018,
		workplace: "VP Product, Yes Madam",
		designation: "AU Small Finance Bank",
	},
];

export default members_2018;
