const members_2022 = [
	{
		name: "Swapnil Agarwal",
		image:"http://drive.google.com/uc?export=view&id=1JbSNJlZzRACdfwX4aBYdMuwsjJ1J_Cq5",
		linkedin: "https://www.linkedin.com/in/swapnilagrawal1/",
		degree: "Mechanical Engineering",
		graduation_year: 2022,
		workplace: "Wells Fargo",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sanchit Agarwal",
		image:"http://drive.google.com/uc?export=view&id=1EkECsBngS7KHRGaY1P-IAkQ9glw-0RS1",
		linkedin: "https://www.linkedin.com/in/sanchit-a-98a9b8ab/",
		degree: "Electrical Engineering",
		graduation_year: 2022,
		workplace: "Societe Generale Global Solution Centre",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ananya Sharma",
		image:"http://drive.google.com/uc?export=view&id=1oVqXvdhpv-Bh7HvpOKcW-YTHB4rLSOjU",
		linkedin: "https://www.linkedin.com/in/ananyasharmaiitkgp/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2022,
		workplace: "Nomura",
		designation: "",
		additional_info: "",
	},
	{
		name: "Vasu Gurram",
		image:"http://drive.google.com/uc?export=view&id=1MsZKHfc2A18FlPILkLW2ZQnFlDUQGnlD",
		linkedin: "https://www.linkedin.com/in/vasu-gurram-a94687177/",
		degree: "Computer Science Engineering",
		graduation_year: 2022,
		workplace: "Sprinklr",
		designation: "",
		additional_info: "",
	},
	{
		name: "Bhavik Jain",
		image:"http://drive.google.com/uc?export=view&id=150-Z1vN0Bv6idv7BGRgiOcWuN6n2Fvvy",
		linkedin: "https://www.linkedin.com/in/bhavik-jain-142545170/",
		degree: "Metallurgical and Materials Engineering",
		graduation_year: 2022,
		workplace: "Accenture",
		designation: "",
		additional_info: "",
	},
	{
		name: "Lokesh Chikkula",
		image:"http://drive.google.com/uc?export=view&id=1FYD87vmNVB9Z_yvhG6Fmy8nyA18VKsyK",
		linkedin: "https://www.linkedin.com/in/lokesh-chikkula-962301186/",
		degree: "Computer Science Engineering",
		graduation_year: 2022,
		workplace: "Mastercard",
		designation: "",
		additional_info: "",
	},
	{
		name: "Tista Kundu",
		image:"http://drive.google.com/uc?export=view&id=12f_TifNJnElZVf4l7UiN3YeLHkPMKBsR",
		linkedin: "https://www.linkedin.com/in/tista-kundu-4433b7172/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2022,
		workplace: "Qualcomm",
		designation: "",
		additional_info: "",
	},
	{
		name: "Apoorv Singh",
		image:"http://drive.google.com/uc?export=view&id=19wTzlXwS6cXgpwDBAFulxS3hNl5H8Ie9",
		linkedin: "https://www.linkedin.com/in/apoorvsingh1610/",
		degree: "Chemical Engineering",
		graduation_year: 2022,
		workplace: "Axis Bank",
		designation: "",
		additional_info: "",
	},
	{
		name: "Aditi Singhania",
		image:"http://drive.google.com/uc?export=view&id=1b79tzRbBBfryFOKQwQT6JQv20_95vNuV",
		linkedin: "https://www.linkedin.com/in/aditi-singhania-436371146/",
		degree: "Electrical Engineering",
		graduation_year: 2022,
		workplace: "Adobe",
		designation: "",
		additional_info: "",
	},
	{
		name: "Shreya Kumari",
		image:"http://drive.google.com/uc?export=view&id=1F86KdT-Rh2jBYfTHTGoorVbQZtiXK2rX",
		linkedin: "https://www.linkedin.com/in/shreya-kumari-bb1517176/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2022,
		workplace: "J.P Morgan",
		designation: "",
		additional_info: "",
	},
	{
		name: "Arghyadeep Bandopadhyay",
		image:"",
		linkedin: "https://www.linkedin.com/in/arghyadeep-bandyopadhyay-672b881a9/",
		degree: "Electrical Engineering",
		graduation_year: 2022,
		workplace: "Samsung R&D Institute",
		designation: "",
		additional_info: "",
	},
];

export default members_2022;
