const members_2019 = [
	{
		name: "Ritwika Chowdhury",
		image:"http://drive.google.com/uc?export=view&id=1pzXp4IY-Jp3fD0aOzuMcVuXpigxgfG8d",
		linkedin: "https://www.linkedin.com/in/ritwika-chowdhury-a70201112/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2019,
		workplace: "unScript.AI(Founder and CEO)",
		designation: "Research Scientist, Intel Labs",
	},
	{
		name: "Raghav Sonavane",
		image:"http://drive.google.com/uc?export=view&id=1u4XEgwncnTbqnhgAX1YEA8MPY_ZcZ4sR",
		linkedin: "https://www.linkedin.com/in/raghavsonavane/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2019,
		workplace: "Sprinklr",
		designation: "",
	},
	{
		name: "Rahul Barnwal",
		image:"http://drive.google.com/uc?export=view&id=1eLisaDK_6mkOh9uwW1ot7mT0miF67Xel",
		linkedin: "https://www.linkedin.com/in/rahul-barnwal-774169a8/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "J.P Morgan",
		designation: "",
	},
	{
		name: "Mohit Pokharna",
		image:"http://drive.google.com/uc?export=view&id=1mb5OiuvDOprxriwB-KHxO_PvYzpjEGUN",
		linkedin: "https://www.linkedin.com/in/mohitpokharna/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "Mercari",
		designation: "",
	},
	{
		name: "Devanand Kedia",
		image:"http://drive.google.com/uc?export=view&id=1781ACBPsheTsiVXdfqqzk_-oIbK9VVVI",
		linkedin: "https://www.linkedin.com/in/devanandkedia/",
		degree: "Electrical Engineer",
		graduation_year: 2019,
		workplace: "HSBC",
		designation: "",
	},
	{
		name: "Rameshwar Bhaskaran",
		image:"http://drive.google.com/uc?export=view&id=18gVaU9Y5O4m7g4wwHm3dFaYRZqyRTD74",
		linkedin: "https://www.linkedin.com/in/rameshwarbhaskaran/",
		degree: "Computer Science Engineering",
		graduation_year: 2019,
		workplace: "Meta",
		designation: "Senior Software Engineer",
	},
	{
		name: "Shivam Agarwal",
		image:"http://drive.google.com/uc?export=view&id=19YMKDY8r160A8R98HcEHoK1EpYR50Cau",
		linkedin: "https://www.linkedin.com/in/shivam207/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "Infiswift Technologies",
		designation: "Computer Vision Engineer, Accenture",
	},
	{
		name: "Arnab Bir",
		image:"http://drive.google.com/uc?export=view&id=1Yp-T7if9AYGBoOZemYgCDZoqLKHJXg2M",
		linkedin: "https://www.linkedin.com/in/arnabbir/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "Phonepe",
		designation: "Google, Flipkart",
	},
	{
		name: "Utkarsh Parasrampuria",
		image:"http://drive.google.com/uc?export=view&id=1s249pPUUJ3qwV7S3iorTcmafVOBFhHTk",
		linkedin: "https://www.linkedin.com/in/utkarsh-parasarampuria/",
		degree: "Computer Science Engineering",
		graduation_year: 2019,
		workplace: "Rawky Studios",
		designation: "Executive Director, Internship, Intuit India",
	},
	{
		name: "Piyush Kumar Singh",
		image:"http://drive.google.com/uc?export=view&id=1uB2G-CUnsi-iZTR7RSH8g_PLXCc6QYt1",
		linkedin: "https://www.linkedin.com/in/piyushk95/",
		degree: "Civil Engineering",
		graduation_year: 2019,
		workplace: "Morgan Stanley",
		designation: "Blackrock",
	},
	{
		name: "Tejus Gupta",
		image:"http://drive.google.com/uc?export=view&id=1lPTfoOhJMhIkQfmm84IiiGIWVAHZnXOG",
		linkedin: "https://www.linkedin.com/in/tejus-gupta-03baa3102/",
		degree: "Computer Science Engineering",
		graduation_year: 2019,
		workplace: "Research Assistant, Robotics Institute",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ashwary Anand",
		image:"http://drive.google.com/uc?export=view&id=1gcuR8d5rgNiPQJ4BDxO-mDRkIUdH8OSl",
		linkedin: "https://www.linkedin.com/in/ashwary-anand-a83642107/",
		degree: "Mechanical",
		graduation_year: 2019,
		workplace: "Rapyuta Robotics",
		designation: "",
		additional_info: "",
	},
	{
		name: "Pranjal Jain",
		image:"http://drive.google.com/uc?export=view&id=1MNle2sqwTI0L6iBba1VIMmrPg-p1h5Uh",
		linkedin: "https://www.linkedin.com/in/pranjal-jain-8759a1b4/",
		degree: "Chemical Engineering",
		graduation_year: 2019,
		workplace: "JP Morgan Chase &Co",
		designation: "",
		additional_info: "",
	},
	{
		name: "Aniket Gattani",
		image:"http://drive.google.com/uc?export=view&id=19TdScPODcHjsdpp2kMFfshwKbW6zE3Te",
		linkedin: "https://www.linkedin.com/in/aniket-gattani-7692b0104/",
		degree: "Mechanical Engineering",
		graduation_year: 2019,
		workplace: "",
		designation: "Amazon, Intuit",
		additional_info: "Rice University",
	},
	{
		name: "Abhinav Arun",
		image:"http://drive.google.com/uc?export=view&id=1Gy1wYMLMkngclxzISwYgGhz9V5XjOn5_",
		linkedin: "https://www.linkedin.com/in/abhinav-arun-432341117/",
		degree: "Mechanical Engineering",
		graduation_year: 2019,
		workplace: "Graduate Teaching Assistant, Georgia Institute of Technology",
		designation: "Innovaccer",
		additional_info: "Georgia Institute of Technology",
	},
	{
		name: "Satyam Behera",
		image:"http://drive.google.com/uc?export=view&id=1z7naz1gGbsnWQfd6-EcbKthoZyhnz3Yi",
		linkedin: "https://www.linkedin.com/in/satyam-behera-916084114/",
		degree: "Metallurgical and Materials Engineering",
		graduation_year: 2019,
		workplace: "",
		designation: "ExxonMobil",
		additional_info: "IIM Calcutta",
	},
	{
		name: "Tushar Sinha",
		image:"http://drive.google.com/uc?export=view&id=1oFqZjHwqe0O_WCkcMpe-ONy8_EwlckuZ",
		linkedin: "https://www.linkedin.com/in/tushar-sinha-a0904412a/",
		degree: "(Instrumentation Engineering) Electrical Engineering",
		graduation_year: 2019,
		workplace: "Navi",
		designation: "JPMorgan Chase & Co",
		additional_info: "",
	},
	{
		name: "Kanav Anand",
		image:"http://drive.google.com/uc?export=view&id=19N0mmQDp6L-gu_xIw-Kb-B3domSCuY6g",
		linkedin: "https://www.linkedin.com/in/kanavanand/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2019,
		workplace: "Co-founder, Flick",
		designation: "Apna, American Express",
		additional_info: "",
	},
];

export default members_2019;
