const members_2023 = [
	{
		name: "Tushar Gupta",
		image:"http://drive.google.com/uc?export=view&id=1N-cb7CeIErUEZ5KkrMsUOTiO4IATlgaf",
		linkedin: "https://www.linkedin.com/in/tushar-gupta14/",
		degree: "Computer Science Engineering",
		graduation_year: 2023,
		workplace: "",
		designation: "",
		additional_info: "",
	},
	{
		name: "Shivansh Sethi",
		image:"http://drive.google.com/uc?export=view&id=1c7oYpkZOVUDo7AKHXwGS0A815gdBMVhh",
		linkedin: "https://www.linkedin.com/in/shivansh-sethi-a53670191/",
		degree: "Mathematics",
		graduation_year: 2023,
		workplace: "",
		designation: "",
		additional_info: "",
	},
	
	{
		name: "Ekansh Jain",
		image:"http://drive.google.com/uc?export=view&id=1KIp8uNT11TtSLRVQp6gMRPUprAz67P0L",
		linkedin: "https://www.linkedin.com/in/ekansh-jain-982452177/",
		degree: "Architecture and Regional Planning",
		graduation_year: 2023,
		workplace: "BlinkIt",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sayantan Kirtaniya",
		image:"http://drive.google.com/uc?export=view&id=1kP5Dyb-Ovb1WYxJO2JK1ZVe9ydYVgSDw",
		linkedin: "https://www.linkedin.com/in/sayantan-kirtaniya/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2023,
		workplace: "John Deer India Pvt Ltd",
		designation: "",
		additional_info: "",
	},
	{
		name: "Abhinav Jha",
		image:"http://drive.google.com/uc?export=view&id=1d2qK8JtvJurEVJw4ND7ml_VyeAJDfsnv",
		linkedin: "https://www.linkedin.com/in/abhinav-jha-431a901a0/",
		degree: "Agriculture and Food Engineering",
		graduation_year: 2023,
		workplace: "TCG Digital",
		designation: "",
		additional_info: "",
	},
	{
		name: "Manasi Bandhaokar",
		image:"http://drive.google.com/uc?export=view&id=1nKJtHAjYXFWa1qsbOzKKk6Vtp4VpE9CX",
		linkedin: "https://www.linkedin.com/in/manasi-bandhaokar-b3715a16b/",
		degree: "Civil Engineering",
		graduation_year: 2023,
		workplace: "",
		designation: "",
		additional_info: "",
	},
	{
		name: "Umang Aditya",
		image:"http://drive.google.com/uc?export=view&id=1C3gZ7SaWwxBMLjMWjhM-jk40N1lY3BXQ",
		linkedin: "https://www.linkedin.com/in/umang-aditya/",
		degree: "Mining Engineering",
		graduation_year: 2023,
		workplace: "Cogoport",
		designation: "",
		additional_info: "",
	},
	{
		name: "Tanishq Bansal",
		image:"http://drive.google.com/uc?export=view&id=1AVABl_WER2TYpQvgKKIeGpwZNuQwkeF1",
		linkedin: "https://www.linkedin.com/in/tanishq-bansal-2104/",
		degree: "Architecture and Regional Planning",
		graduation_year: 2023,
		workplace: "BlinkIt",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sai Chandan",
		image:"http://drive.google.com/uc?export=view&id=1Euf6oVCq8DYiVNJmcP7IsHBahEfiAKt4",
		linkedin: "https://www.linkedin.com/in/saichandankadarla/",
		degree: "",
		graduation_year: 2023,
		workplace: "Infonetica",
		designation: "Founding Team Member, Expresso",
		additional_info: "Student Member",
	},
	{
		name: "Archit Rungta",
		image:"http://drive.google.com/uc?export=view&id=1PFhfsKa9QCZwrdOY_1A3GMUI5BnVBjSw",
		linkedin: "https://www.linkedin.com/in/archit-rungta-6675a288/",
		degree: "Mathematics",
		graduation_year: 2023,
		workplace: "Jane Street",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ikshu Kumbhar",
		image:"http://drive.google.com/uc?export=view&id=1Zin0XN98rnF3pgd41_gSIycj95rrNxEE",
		linkedin: "https://www.linkedin.com/in/ikshu-manjan-kumbhar-193b291a1/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2023,
		workplace: "Deloitte",
		designation: "",
		additional_info: "",
	},
	{
		name: "Safeer Subhan",
		image:"http://drive.google.com/uc?export=view&id=1bFyoP3kXgIacoWp6q2tXT8ZwUTmakBZe",
		linkedin: "",
		degree: "",
		graduation_year: 2023,
		workplace: "",
		designation: "",
		additional_info: "",
	},
	{
		name: "Soumyadeep Saha",
		image:"http://drive.google.com/uc?export=view&id=1CYNHcb1-GI9_p9AUcSZ4Dj4hpxamZk5N",
		linkedin: "https://www.linkedin.com/in/soumyadeep-saha-711a23183/",
		degree: "Mechanical Engineering",
		graduation_year: 2023,
		workplace: "John Deer India Pvt Ltd",
		designation: "",
		additional_info: "",
	},
	
	{
		name: "Arnab Bala",
		image:"http://drive.google.com/uc?export=view&id=12ZsWl2YY6QD3k-A0HP0S4pIZ-qsAd3Bo",
		linkedin: "https://www.linkedin.com/in/arnab-bala-20424016b/",
		degree: "Financial Engineering",
		graduation_year: 2023,
		workplace: "",
		designation: "",
		additional_info: "",
	},
	{
		name: "Onkar Sabnis",
		image:"http://drive.google.com/uc?export=view&id=1sAP5WPzx0Q5yuNrkqvkPiTMcc9tzsh6H",
		linkedin: "https://www.linkedin.com/in/onkar-sabnis-883094170/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "American Express",
		designation: "NLP Research Analyst, Enterprai",
		additional_info: "Advisor",
	},
	{
		name: "Shailesh Nanisetty",
		image:"http://drive.google.com/uc?export=view&id=1UlDZbZtvAa50gON-5OWsYlwBZiv3daBU",
		linkedin: "https://www.linkedin.com/in/shaileshnanisetty007/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2023,
		workplace: "University of Toronto",
		designation: "",
		additional_info: "MS, Associate Member",
	},
	{
		name: "Shivansh Junwal",
		image:"http://drive.google.com/uc?export=view&id=1IP2C8VV0D5vWXu6YW8equrKId0BDZDpd",
		linkedin: "https://www.linkedin.com/in/shivansh-junwal-8b3b28148/",
		degree: "Economics",
		graduation_year: 2023,
		workplace: "Cars24",
		designation: "Co-Founder, BusMaps",
		additional_info: "Associate Member",
	},
	{
		name: "Abhilash Sinha",
		image:"http://drive.google.com/uc?export=view&id=1xXDtIoKnCS5PbTXfQAtlwKKHBU_kpdRt",
		linkedin: "https://www.linkedin.com/in/abhilash-sinha-1216a11b3/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "BNY Mellon",
		designation: "",
		additional_info: "",
	},
	{
		name: "Abhranil Chandra",
		image:"http://drive.google.com/uc?export=view&id=10nvK_iAqbjxFj68WYsTo2-Gy9sW1qVmN",
		linkedin: "https://www.linkedin.com/in/abhranil-chandra-462332136/",
		degree: "Mechanical Engineering",
		graduation_year: 2023,
		workplace: "Palitronica Inc",
		designation: "",
		additional_info: "Masters",
	},
	{
		name: "Arun Kumar Nayak",
		image:"http://drive.google.com/uc?export=view&id=1fsnWBBaGppHNBfdDpWWiGK2wxu04tZ84",
		linkedin: "https://www.linkedin.com/in/arun-nayak-7104a51aa/",
		degree: "Metallurgical Engineering",
		graduation_year: 2023,
		workplace: "UIDAI",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ayush Surana",
		image:"http://drive.google.com/uc?export=view&id=1c_oxQ5nhg1gL3GcISP-SNT7C4LRmUfke",
		linkedin: "https://www.linkedin.com/in/ayushsurana1/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "Oracle",
		designation: "",
		additional_info: "",
	},
	{
		name: "Chinmay Jain",
		image:"http://drive.google.com/uc?export=view&id=13bEnvMJHeqslrqIFJ7D_iTnyJCdcSrfm",
		linkedin: "https://www.linkedin.com/in/chinmay-jain-a833aa193/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "Walmart",
		designation: "",
		additional_info: "",
	},
	{
		name: "Divyangna Sharma",
		image:"http://drive.google.com/uc?export=view&id=14YCj3oFl6L7BHkcuNDK8_0anujbMFIH5",
		linkedin: "https://www.linkedin.com/in/divyangna-sharma-5354291b5/",
		degree: "Chemistry",
		graduation_year: 2023,
		workplace: "JP Morgan Chase & Co.",
		designation: "",
		additional_info: "",
	},
	{
		name: "Rahul Mandal",
		image:"http://drive.google.com/uc?export=view&id=1mrZTanxu2FrDbVMhZYAw0YA-nzE2hjF6",
		linkedin: "https://www.linkedin.com/in/tesla132/",
		degree: "Mechanical Engineering",
		graduation_year: 2023,
		workplace: "",
		designation: "",
		additional_info: "MBA",
	},
	{
		name: "Ratnesh Bhosale",
		image:"http://drive.google.com/uc?export=view&id=11hvpanGr65Wbp5yHNjYBDav-ysbb1pez",
		linkedin: "https://www.linkedin.com/in/ratneshbhosale999/",
		degree: "Mechanical Engineering",
		graduation_year: 2023,
		workplace: "DTDC",
		designation: "",
		additional_info: "",
	},
	{
		name: "Roshni Kar",
		image:"http://drive.google.com/uc?export=view&id=1etk2cvAfxO_P7LrUer1mMy1wkPYmkHCU",
		linkedin: "https://www.linkedin.com/in/roshni-kar/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "Pine Labs",
		designation: "",
		additional_info: "",
	},
	{
		name: "Shalini Bansal",
		image:"http://drive.google.com/uc?export=view&id=1x7xfMeOz4Hf2x1JL6vWCWrP8Ui5QiP3Q",
		linkedin: "https://www.linkedin.com/in/shalini-bansal-9314431b4/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "American Express",
		designation: "",
		additional_info: "",
	},
	{
		name: "Murali Manohar",
		image:"http://drive.google.com/uc?export=view&id=1sEOMNNX5p78YtvEEIW7BBkBbvyMoGGno",
		linkedin: "https://www.linkedin.com/in/murali-manohar-bb848a1a7/",
		degree: "Mechanical Engineering",
		graduation_year: 2023,
		workplace: "Axis Bank",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ronak Agarwal",
		image:"http://drive.google.com/uc?export=view&id=15IqU42qTeNlAb4bF577Y_LQB2_56Mftq",
		linkedin: "https://www.linkedin.com/in/ronakagarwal3434/",
		degree: "Chemical Engineering",
		graduation_year: 2023,
		workplace: "Honeywell",
		designation: "",
		additional_info: "",
	},
	{
		name: "Yash Agrawal",
		image:"http://drive.google.com/uc?export=view&id=1WMQ4qdp9WSaUpSn644jNZf6ziDSczGzm",
		linkedin: "https://www.linkedin.com/in/yash-agrawal-6b4253194/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2023,
		workplace: "Bidgely",
		designation: "",
		additional_info: "",
	},
];

export default members_2023;
